# -*- coding: utf-8 -*-
"""3_Dimensiones_tensores_reshape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vtYE45PVeCTW399BtA7SwkRetz08o7QR
"""

import numpy as np

"""#Scalar"""

"los escalares son numeros unicos"
x = np.array(42)
print(x.shape)
"n dim nos ayuda a sabaer las dimensiones de un array"
x.ndim

"""#Vectores"""

"Tiene forma de lista"
x = np.array([12,5,89,63,8,23,37,4765])
print(x.shape)
"n dim nos ayuda a sabaer las dimensiones de un array"
x.ndim

"""#Matriz"""

"Tiene forma de lista"
x = np.array([[12,5,89,63,8,23,37,4765],
              [12,5,89,63,8,23,37,4765]])
print(x.shape)
"n dim nos ayuda a sabaer las dimensiones de un array"
x.ndim

"""#Tensor"""

"Tiene forma de lista"
x = np.array([[[12,5,89,63,8,23,37,4765],
              [12,5,89,63,8,23,37,4765]],
              [[12,5,89,63,8,23,37,4765],
              [12,5,89,63,8,23,37,4765]],
              [[12,5,89,63,8,23,37,4765],
              [12,5,89,63,8,23,37,4765]]])
print(x.shape)
"n dim nos ayuda a sabaer las dimensiones de un array"
x.ndim

"""#Reshape"""

x = np.array([[0,1],
          [2,3],
          [4,5],
          [6,7]])
x.shape

x.reshape(8,1)

x.reshape(2,4)

"""#Transpose"""

y = np.transpose(x)
print(y.shape)
print(x.shape)

x.T